name: shormeh
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0 "

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.13.4
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.4
#  rxdart: ^0.27.1
#  auto_size_text: ^1.1.1
#  intro_slider: ^2.4.3
#  image_auto_slider: ^0.0.3
#  direct_select: ^1.0.3
#  awesome_dialog: ^2.1.0
#  form_bloc: ^0.20.4
  carousel_slider: ^4.0.0
  google_maps_flutter: ^2.1.0
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  location: ^4.3.0
  app_settings: ^4.1.1
  android_intent: ^2.0.2
  modal_bottom_sheet: ^2.0.0
  flutter_slidable: ^0.6.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.2
  firebase_core: ^1.10.0
  flutter_rating_bar: ^4.0.0
  lottie: ^1.2.1
  url_launcher: ^6.0.13
#  flutter_phoenix: ^1.0.0
#  flutter_native_splash: ^1.2.0
#  webview_flutter: ^1.0.7
#  font_awesome_flutter: ^9.1.0
  localization: ^1.1.0
  flutter_translate: ^3.0.1
  flutter_svg: ^0.23.0+1
  hexcolor: ^2.0.5
  curved_navigation_bar: ^1.0.1
  dio: ^4.0.3
#  geolocation: ^1.1.2
  geopoint: ^1.0.0
  intl: ^0.17.0
#  lazy_load_scrollview: ^1.3.0
#  pagination: ^0.1.0
#  persistent_bottom_nav_bar: ^4.0.2
#  double_back_to_close: ^2.0.0
  infinite_scroll_pagination: ^3.0.0
  transparent_image: ^2.0.0
  pin_code_fields: ^7.3.0
  overlay_support: ^1.2.1
  badges: ^2.0.1
  flutter_html: ^2.1.5
  permission_handler: ^8.3.0
  font_awesome_flutter: ^9.2.0
  webview_flutter: ^2.3.1






dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
#     - assets/images/backgroundHome.png
#     - assets/images/location.png
#     - assets/images/delivery.png
#     - assets/images/loginBackground.png
#     - assets/images/logo.png
#     - assets/images/alarm.png
#     - assets/images/contact.png
#     - assets/images/info.png
#     - assets/images/mobile.png
#     - assets/images/newspaper.png
#     - assets/images/orders.png
#     - assets/images/request.png
#     - assets/images/user.png
#     - assets/images/points.png
#     - assets/images/check-circle.svg
#     - assets/images/logout.png
     - assets/lottieRate.json
     - assets/lottieBoy.json
     - assets/lottieBranche.json
     - assets/lottieHome.json
     - assets/i18n/
#     - assets/i18n/ar.json
#     - assets/images/delete.png
#     - assets/images/edit.svg
#     - assets/images/truck.svg
#     - assets/images/comment.svg
#     - assets/images/512.png
#     - assets/images/group1.png
#     - assets/images/Group 9610.png



  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal.ttf